memo/Controllers/memodbsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using memo.Models;

namespace memo.Controllers
{
    public class memodbsController : Controller
    {
        private Entities db = new Entities();

        // GET: memodbs
        public ActionResult Index()
        {
            return View(db.memodb.ToList());
        }

        // GET: memodbs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            memodb memodb = db.memodb.Find(id);
            if (memodb == null)
            {
                return HttpNotFound();
            }
            return View(memodb);
        }

        // GET: memodbs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: memodbs/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,detail,state")] memodb memodb)
        {
            if (ModelState.IsValid)
            {
                db.memodb.Add(memodb);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(memodb);
        }

        // GET: memodbs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            memodb memodb = db.memodb.Find(id);
            if (memodb == null)
            {
                return HttpNotFound();
            }
            return View(memodb);
        }

        // POST: memodbs/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,detail,state")] memodb memodb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(memodb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(memodb);
        }

        // GET: memodbs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            memodb memodb = db.memodb.Find(id);
            if (memodb == null)
            {
                return HttpNotFound();
            }
            return View(memodb);
        }

        // POST: memodbs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            memodb memodb = db.memodb.Find(id);
            db.memodb.Remove(memodb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

memo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - memo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Memo", "Index", "memodbs", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - asp.net 期末作業 1101137202 謝韶華 + 1101137212 陳玠任</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>